[build]
target-dir = "../godot/addons/livestream-rust/bin"

[target.wasm32-unknown-emscripten]
rustflags = [
    # "-C", "link-args=-pthread", # /!\ Read 'Thread support' below regarding this flag
    # "-C", "target-feature=+atomics", # /!\ Read 'Thread support' below regarding this flag
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "llvm-args=-enable-emscripten-cxx-exceptions=0",
    "-Z", "default-visibility=hidden",
    "-Z", "link-native-libraries=no",
    "-Z", "emscripten-wasm-eh=false",
]